service: hello-world
provider:
  name: aws
  runtime: nodejs8.10
  stage: beta
  region: ap-northeast-1
  profile: serverless-training
  apiKeys:
    - sls-training

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          private: true
